trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  autoCancel: false
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages:
  - stage: build
    jobs:
      - template: jobs/devops-secure-scanning.yml@ado-pipeline-templates

      - job: codeql
        steps:
        - task: AdvancedSecurity-Codeql-Init@1
          displayName: Initialize CodeQL
          inputs:
            # build mode `none` is supported for C# and Java, and JavaScript is an interpreted language
            # and build mode `none` has no impact on JavaScript analysis
            languages: 'csharp, java, javascript' 
            buildtype: 'none'

        - task: AdvancedSecurity-Codeql-Analyze@1
          displayName: Perform CodeQL Analysis