trigger:
  branches:
    include:
      - "main"

pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages:
- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: spn-portal-bots-production
    azureEnvironment: portal-bots-Production
    vmEnvironment: portal-bots-dedi-prd
    environmentName: "prd"