trigger:
  branches:
    include:
      - main

schedules:
  - cron: "0 3 * * 4"
    displayName: "Weekly Release (Thu 03:00 UTC)"
    branches:
      include:
        - main
    always: true

pr: none

pool:
  vmImage: 'ubuntu-latest'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages:
- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: spn-portal-bots-production
    azureEnvironment: portal-bots-Production
    vmEnvironment: portal-bots-dedi-prd
    environmentName: "prd"